### PR TITLE
Fix #76

### LINKED ISSUE #76: Jenkins cleanup script doesn't work for a multi-module repository

### PR DESCRIPTION
**Pull request by cvarjao**
Fixes #76

### CODE REVIEW

**Comment by patricksimonian** [comment]
I think we need to start providing guidance on how to upgrade your pipeline as we introduce patches to the bcdk. It isn't as simple as re running the generators it looks like because you may have tailored your jenkins deployment / pipeline cli scripts.

I wonder if we can make some conventions around customization so that we can allow seamless upgrades.

**Comment by cvarjao** [comment]
Yes. That is what I used to fix/help @DerekRoberts

**Comment by DerekRoberts** [comment]
+1

**Comment by patricksimonian** [comment]
can we merge this?

**Pull request merged**
